version: 2.1

orbs:
  browser-tools: circleci/browser-tools@x.y

jobs:
  build-and-test:
  docker:
    - image: 'cimg/node:13.12-browser'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  sample:
    jobs:
      - build-and-test